### ISSUE TITLE
Add Rollback Functionality

### ISSUE THREAD

**Issue by rjhaikal** [ansible-lockdown/UBUNTU20-CIS#127]
**Question**
we've identified the need for a rollback mechanism. This is crucial for addressing emergency situations or issues that may arise post-hardening. Can I safely perform a rollback after hardening? If not, I would like to request the addition of a rollback feature.

**Expected Steps**
1. Identify the specific changes made during the hardening process that need to be reverted during a rollback.
2. Implement a playbook or playbook steps that will undo the hardening changes safely.
3. Test the rollback functionality in various scenarios to ensure reliability.

**Environment (please complete the following information):**
- Operating System: Ubuntu 20.04
- Ansible 2.9+
- Python 3.6+

**Comment by diepes** [comment]
Just my opinion:
Due to ansible being imperative, this is not realistic, how would you know the original settings for everything as OS updates change?
You probably have to CIS secure test systems and verify everything is 100%.

I think it might be better to create role that address the main risk areas you identify.
1. User access - Sudoers and SSH allow - maybe have a serial console option to recover?
2. firewall ufw - sudo ufw disable

**Comment by uk-bolly** [comment]
hi @rjhaikal 

Thank you for raising this question, As @diepes as pointed out this is something that is not really a practical offer to enable rollback, as the amount of captured data for all systems would be unmanageable especially for patching etc takes place and removal of installed packages.
As pointed out in this case, you are better to set those requirements as you expect to find them (maybe using config mgmt like ansible) and then either skip them in here or adjust the settings for your systems, so this playbook is aligned to your requirements and idempotancy plays it part and makes no changes as part of this playbook.

I hope that helps.

Many thanks

uk-bolly

**Comment by rjhaikal** [comment]
Alright, thank you, guys. I agree with your opinions, and it makes more sense. Thanks for all your suggestions.
